### ISSUE TITLE
install Singular in Windows

### ISSUE THREAD

**Issue by jkwGavin** [wbhart/Singular.jl#52]
I am trying to install Singular in a Windows 10 machine. When I ran Pkg.build("Singular"), I got 
Error: Error building `Singular`:
│ ERROR: LoadError: LoadError: Your platform ("x86_64-w64-mingw32", parsed as "x86_64-w64-mingw32-gcc8-cxx11") is not supported by this package!
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\jianwei\.julia\packages\Singular\GGfzi\deps\build_libntl.v10.5.0.jl:26
│  [3] include(::Module, ::String) at .\Base.jl:377
│  [4] include(::String) at C:\Users\jianwei\.julia\packages\Singular\GGfzi\deps\build.jl:45
│  [5] top-level scope at C:\Users\jianwei\.julia\packages\Singular\GGfzi\deps\build.jl:45
│  [6] eval(::Module, ::Any) at .\boot.jl:331
│  [7] top-level scope at C:\Users\jianwei\.julia\packages\Singular\GGfzi\deps\build.jl:45
│  [8] include(::String) at .\client.jl:439
│  [9] top-level scope at none:5
│ in expression starting at C:\Users\jianwei\.julia\packages\Singular\GGfzi\deps\build_libntl.v10.5.0.jl:22
│ in expression starting at C:\Users\jianwei\.julia\packages\Singular\GGfzi\deps\build.jl:19

Is there any workaround? 

Thank you so much

Jianwei

**Comment by wbhart** [comment]
Hi Jianwei,

This is not the official Singular.jl package. It's here:

https://github.com/oscar-system/Singular.jl

However, I happen to know the answer to your question in this case.

Unfortunately mingw is not supported by Singular itself and probably never will be, so there is no workaround. On Windows your only option is the Windows Subsystem for Linux, where Singular.jl works.

**Comment by jkwGavin** [comment]
Thank you so much for your response. It's very helpful. 

JW
